### ISSUE TITLE
Kotlin DSL: `fileTree(mapOf(...))` has unexpected behavior in Gradle 6

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#11335]
### Expected behaviour

The expression `fileTree(mapOf("dir" to dir, "include" to listOf(glob)))` should be equivalent to `fileTree(dir) { include(listOf(glob)) }`.

### Actual behaviour

The expression `fileTree(mapOf("dir" to dir, "include" to listOf(glob)))` is equivalent to `fileTree(baseDir = mapOf(..))` which makes no sense.

## Tasks
- [x] Ensure the expected behaviour
- [ ] Ensure there are no other overloads missing from the combined `KotlinScript` + implicit receiver API surface compared to the 5.x script templates
- [ ] Update the upgrade guide if we decide not to support missing overloads

**Comment by eskatos** [comment]
Fixed by #11347, will ship in Gradle 6.0.1
See #11385 about the rationale for the underlying breaking change.
Closing
