### ISSUE TITLE
Central declaration of dependencies

### ISSUE THREAD

**Issue by melix** [gradle/gradle#15352]
This epic links all issues related to central declaration of dependencies for its initial release.

Before commenting on this issue, please take a look at:
   - the [current documentation for this feature](https://docs.gradle.org/nightly/userguide/platforms.html#sub:central-declaration-of-dependencies)
   - the [specification document](https://github.com/gradle/gradle/files/5646826/2020-12-05-Central.declaration.of.dependencies.Shared.externally.pdf)

Note: the fact of having an external file (whatever the format is) in addition to the settings API is still heavily debated internally. Do not assume it will be present when this feature is released.

## Considered

- [ ] [Make version catalogs accessible from precompiled script plugins](https://github.com/gradle/gradle/issues/15383)

## Closed

- [x] [Introduce a settings DSL for central dependency declaration](https://github.com/gradle/gradle/issues/14896)
- [x] [Polish central declaration of dependencies](https://github.com/gradle/gradle/issues/15010)
- [x] [Add support for the strict version shorthand notation in settings DSL and TOML parser](https://github.com/gradle/gradle/issues/15022)
- [x] [Add a version catalog plugin](https://github.com/gradle/gradle/issues/15019)
- [x] [Make the dependencies model builder more convenient](https://github.com/gradle/gradle/issues/15030)
- [x] [Improve traceability of imported dependencies](https://github.com/gradle/gradle/issues/15061)
- [x] [Make sure the dependencies model supports no version](https://github.com/gradle/gradle/issues/15063)
- [x] [Alternate implementation for bundle and version accessors](https://github.com/gradle/gradle/issues/15091)
- [x] [Initial documentation for the version catalog](https://github.com/gradle/gradle/issues/15142)
- [x] [Fast way to declare dependencies in `buildSrc` for autocompletion without a full rebuild](https://github.com/gradle/gradle/issues/9008)
- [x] [Use a named object container for the catalogs](#15301)
- [x] [Make catalogs support nested catalogs](#15307)
- [x] [Give access to catalogs from binary plugins](https://github.com/gradle/gradle/pull/15443)
- [x] [Not possible to use libs.xy based on TOML file inside of custom configuration with closure](https://github.com/gradle/gradle/pull/15444)
- [x] [Add a spec version number to the catalog file](https://github.com/gradle/gradle/issues/15329)

**Comment by tprochazka** [comment]
I did a simple and ugly script that can generate TOML for an existing project and then replace dependencies with aliases.
For testing purposes of this feature. Nothing special, I'm using it for migration my project, maybe it can be useful for someone else.
Definitely a great antipattern example of how to write something like this ;-) 
https://github.com/tprochazka/gradle-toml-dependencies-migration-script

**Comment by gildor** [comment]
Is there any roadmap/feature list?

Particularly, I'm interested in following progress about the support of precompiled script plugins (or maybe plugins in general, make generated dependencies accessors available on classpath of plugin, at least for buildSrc)

**Comment by melix** [comment]
Updated the description to reflect the ZenHub epic. Really sad this isn't done by default :(

**Comment by JavierSegoviaCordoba** [comment]
I would like to share versions between toml files. My idea is having a `version.toml` which only has all versions used by all project dependencies and to use them inside, for example, `common-dependencies.toml`, `jvm-dependencies.toml`, etc.

Currently, if I declare a version in a different toml file I can't use it in another file.

**Comment by ZakTaccardi** [comment]
Two questions on the implementation of this feature:

1. Will changes to dependency versions with this approach still require full classpath invalidation? Like defining versions in buildSrc currently does?
2. Will custom dependency versions be injectable via `gradle properties`/`local.properties`? For example, we by default rely on a stable version of Android Gradle Plugin, but a dev may choose to use a alpha version locally to test it out. For example:

```properties
#gradle.properties
agpVersion=4.1.0
```

```properties
#local.properties
agpVersion=4.2.0-alpha01
```

**Comment by melix** [comment]
> Currently, if I declare a version in a different toml file I can't use it in another file.

That is not quite correct. The current implementation allows merging multiple sources (TOML files) into a single catalog:

```
versionCatalog {
   libs {
       from(files("gradle/version.toml"))
       from(files("gradle/common-dependencies.toml"))
       ...
   }
}
```

**Comment by melix** [comment]
@ZakTaccardi 
>Will changes to dependency versions with this approach still require full classpath invalidation? Like defining versions in buildSrc currently does?

No, please look at the spec above. Only a change to the schema (the aliases) would cause invalidation. Changes to versions or coordinates wouldn't.

> Will custom dependency versions be injectable via gradle properties/local.properties? 

No, this is out of scope of this version. We are thinking about standard ways to do it, to address the use case of testing a new version of a library.

**Comment by JavierSegoviaCordoba** [comment]
@melix it is working, is it planned to add a flag to allow one file can be used by all catalogs?

**Comment by melix** [comment]
>  it is working, is it planned to add a flag to allow one file can be used by all catalogs?

No, and I don't think we should. The composition mechanism is order sensitive, so that you can pick dependencies from one catalog, override versions from another, etc. Also the recommendation would be to keep your catalog in a single file as much as possible: anything not following the recommendation would likely make IDE support more complicated to do.

**Comment by gesellix** [comment]
I'm sure that declarations themselves won't help with tools like Dependabot (https://github.com/dependabot/dependabot-core/issues/2238), but maybe the new declarations in combination with similar structured lock files might be considered?

**Comment by melix** [comment]
Combination or using existing files was considered but discarded because they talk about different things. For dependency verification, because it's highly structured, an XML file was considered the best choice. For dependency locking,` git diff` was considered the most important part, so we used a plain text file. For TOML, ease-of-write was considered important, in order to avoid competing with `gradle.properties` and custom file formats.

The question is whether we should use an existing format, say XML, for “consistency”, or introduce the same data into existing files to avoid the multiplication of sources and formats.

There are two different concerns in this question. The first one is whether we would reuse an existing file to model this data, and the second one is whether we should reuse a format we already use somewhere else instead.

To the first question, we answer that the data should be kept separate. Those files talk about different things:
- the dependency lock files shouldn’t be written by users. It’s an internal, state file used by Gradle. It’s a serialization format, which is optimized for readability in diffs.
- the dependency verification file talks about all resolved artifacts in a build, which includes plugins, jars, POM files, … For a single dependency declaration, multiple files can be resolved. We even verify any file which is downloaded during a build via the resolution engine. It includes transitive dependencies, for example. To this extent, the verification file is the most painful of all files because it requires an extensive description of the result of resolution, and contains information about how to solve verification problems: missing signatures, missing checksums, … For this reason, it’s disabled by default and most projects don’t use it. We think that the way Gradle declares verification is better than what Bazel does, for example: Bazel mixes the dependency declaration with the artifact verification, ignoring metadata, ignoring that the jars can come from different repositories, ignoring that the actually resolved artifacts can be different, or ignoring classified dependencies. It also forces to declare first level dependencies for transitives verification.
- the catalog file is just, as it name states, a catalog of dependencies to pick from. It’s about first level dependencies and conveniences for centralizing the declaration in a multi-project build. It doesn’t force anyone to use those dependencies, not use their versions: they can be overwritten in the build script for example. It doesn’t care either about where they are used, in particular in which configurations.

So the remaining question is whether we should use an already existing file format. Our point of view on this is that to each use case we should provide the easiest solution. Please refer to the spec for a detailed explanation of why we prefer this format over another one.

For the sake of the discussion, let’s imagine that we make a mistake and that tomorrow, we want to use a different file format. Because it’s an external file, which isn’t a custom code DSL, we can actually very easily, on a future Gradle version, automatically convert one format to another. Arguably though, we would still have to support previously published catalogs which use the TOML file format as a serialization format.

**Comment by gesellix** [comment]
Thanks for that quick and thorough explanation! Assuming that other tools shouldn't try to understand Gradle's internal file formats, I ask myself whether the Tooling API might help so that Gradle exposes an explict way of analysing and finding updated dependencies... but that discussion diverges from the topic of this issue :)

**Comment by melix** [comment]
Telling you about the latest versions of dependencies is an independent feature which can be implemented separately. We want it, but don't have the bandwidth to work on it.

**Comment by kashike** [comment]
I really need to ask... why start using TOML for this when YAML is already bundled with Gradle, and there's nothing wrong with YAML?

**Comment by melix** [comment]
YAML is the last thing I would ever choose :) The rationale is in the design specification linked in the issue description. YAML is not "bundled with Gradle", I don't know what you're referring to?

**Comment by kashike** [comment]
Ah, seems only platform-natvie bundles YAML - my mistake.

**Comment by ljacomet** [comment]
A first version of this will ship with Gradle 7.0.
I will close this and the team will be waiting for feedback on the feature.

**Comment by dsvensson** [comment]
@ljacomet is `testImplementation(enforcedPlatform(libs.foo.bar.baz))` work? I need to add `.get()` to the end for it to compile.

**Comment by ljacomet** [comment]
@dsvensson It should work. I would recommend that you craft a reproducer and open a separate issue for this specific point.

**Comment by ZakTaccardi** [comment]
> > Will custom dependency versions be injectable via gradle properties/local.properties?
> 
> No, this is out of scope of this version. We are thinking about standard ways to do it, to address the use case of testing a new version of a library.

@melix is there an existing issue tracking this feature request? or is it something I should file

**Comment by brutall** [comment]
@melix 
I'm pretty confused with this feature. I have a multi-module project and I would like to share the dependencies config between submodules. As this is a new project, I would like to use what is considered the cleanest, the best or the most standard approach for future Gradle projects. I don't have any fancy needs, just share dependencies and while it seems version catalogs were designed specifically for this requirement, I didn't really find a way to use them without some hacks or workarounds.

This is what I tried:

1. We can put dependencies in `build.gradle.kts` of each submodule, but it sounds like a lot of repeating ourselves and I guess the "Central declaration of dependencies" was supposed to help mitigate this problem.
2. We can use `allprojects{}`, `subprojects{}` to configure submodules, but this is discouraged, it is not natively supported by version catalogs and probably won't be: #16634
3. We can use preferred method of sharing build logic - convention plugins, but it makes things even more complicated:
    * If we add a version catalog to the main project, it won't be available for plugins. If we add it to `buildSrc`, it won't be easily available to `build.gradle.kts` files of our project. I guess we can hack it somehow to expose the catalog to our build scripts or just import the same `TOML` file in both projects.
    * More importantly, version catalog is automatically accessible only from `buildSrc/build.gradle.kts`, but not from convention plugins, where we need to use it. Again, it may be possible to access it somehow, but I don't really know how, it is undocumented. If I understand correctly, #15383 is related to this problem.

What do I miss here? What is the standard way of using version catalogs in real-life scenarios? The official documentation only explains how to access the catalog from a build script, but it doesn't really answer the question, how to use these catalogs in real projects that could require them.

Of course I understand this feature is incubating and may not fit all use cases well. I'm just concerned as I think I described the most basic or common user scenario for using version catalogs and still it seems pretty hard to do. Please advise.
