### ISSUE TITLE
Provide Configuration Time insights to Build Scans

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1605]
- [X] How long did each script take to evaluate?
- [X] How long did each plugin take to evaluate?
- [ ] How much did each script/plugin contribute to configuration time overall (including `afterEvaluate` and similar hooks)
- [X] What network requests were made during configuration time? (e.g. dependency resolution at configuration time, plugin resolution, `apply from: someUrl` etc.)
- [ ] How much file I/O occurred during configuration time? (e.g. walking directory trees at config time instead of at execution time)

**Comment by adammurdoch** [comment]
Also: garbage collection pauses, and other interesting GC metrics.
