### ISSUE TITLE
Improve usability for build operations generated for script execution

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#1682]
@adammurdoch commented on [Tue Mar 28 2017](https://github.com/gradle/performance/issues/503)

This is just a bucket of issues, should be split up:

- [x] Don't generate a build operation for scripts that don't exist, or at least indicate this.
- [ ] Describe which build an init script is being applied to, when a buildSrc build or child builds are present. Currently the display name for these operations is 'Apply init script 'x' to build'. For the settings and build scripts we nominate which build the target belongs to.
- [x] We might remove the target from the (short display) name, as the target is implied by the context.
- [x] We might use short relative paths to the scripts instead of absolute paths in the name.

These following things aren't directly related to script execution, but are made more confusing when we add in the script execution operations:

- [ ] There is no build operation around the loading of each child build, and the operation for running the init and settings script for the child build is nested inside running the settings script for the parent build. We should add some context here (it's a separate issue that this happens while running the parent build's settings script and isn't deferred).
- [ ] The build operation around configuring each child build doesn't describe which build is being configured, so the build script execution for child builds (which happens first) looks like it's running as part of configuring the parent build and that we're configuring the build a bunch of times.
- [x] The short display name for configuring project operations is simply the project path. This used to make sense when these were all direct children of 'configure build' or another project's configure operation. Now, these can be interleaved with the build script execution operations and this short display name isn't quite so clear in this case.

**Comment by jjohannes** [comment]
> We might remove the target from the (short display) name, as the target is implied by the context.
> We might use short relative paths to the scripts instead of absolute paths in the name.

Adding to this: 
We should attach a proper `BuildOperationDetails` object to the operation. It should contain a `operationDescriptor` for consumption in build scans. For that we should consider the `TextResource` object provided by `ScriptPlugin.getSource()`. However, that does not contain any information about the `target`. The target could only be determined from the `name` of the operation.

in general, We could also consider to allow a list of `operationDescriptor` objects. This would allow us to attach more information without the need to create addition objects. In the case of this build operation, we could then add `source` and `target` objects as `operationDescriptor`.

https://github.com/gradle/gradle/blob/db51a75508ddd5ca951140a86c3ef7b5baa8d28d/subprojects/core/src/main/java/org/gradle/configuration/BuildOperationScriptPlugin.java#L47-L47

**Comment by eskatos** [comment]
Having a typed set of "descriptors" on an operation sounds good. Maybe `T getDescriptor(Class<T>)` would be better than a list. Consumers have to rely on `instanceof` already anyway.

**Comment by oehme** [comment]
> In general, we could also consider to allow a list of operationDescriptor objects. This would allow us to attach more information without the need to create addition objects. 

You'd create a list, so you haven't saved any memory. And it would be more awkward than a single, strongly typed object. The build scan plugin should be able to use `descriptor instanceof WhatEver` to figure out what kind of operation it is looking at.

**Comment by jjohannes** [comment]
Some parts of this issue are already addressed as part of #1781:

> Don't generate a build operation for scripts that don't exist, or at least indicate this.

#1781 -  https://github.com/gradle/gradle/pull/1781/commits/f2c651969550b2fa4bad0e835214cbb315b61b1d 

> We might remove the target from the (short display) name, as the target is implied by the context.

#1781 -  https://github.com/gradle/gradle/pull/1781/commits/f2c651969550b2fa4bad0e835214cbb315b61b1d 

> We might use short relative paths to the scripts instead of absolute paths in the name.

#1781 -  https://github.com/gradle/gradle/pull/1781/commits/f2c651969550b2fa4bad0e835214cbb315b61b1d 

> The short display name for configuring project operations is simply the project path. This used to make sense when these were all direct children of 'configure build' or another project's configure operation. Now, these can be interleaved with the build script execution operations and this short display name isn't quite so clear in this case.

#1781 -  https://github.com/gradle/gradle/pull/1781/commits/d4a8da0898a3644ac13aba08f749bc9389b0269d

> We should attach a proper BuildOperationDetails object to the operation. It should contain a operationDescriptor for consumption in build scans. For that we should consider the TextResource object provided by ScriptPlugin.getSource().

#1781 -  https://github.com/gradle/gradle/pull/1781/commits/f2c651969550b2fa4bad0e835214cbb315b61b1d 

**TODO Init Scripts / buildSrc / Child Builds**

- Describe which build an init script is being applied to, when a buildSrc build or child builds are present. Currently the display name for these operations is 'Apply init script 'x' to build'. For the settings and build scripts we nominate which build the target belongs to.
- There is no build operation around the loading of each child build, and the operation for running the init and settings script for the child build is nested inside running the settings script for the parent build. We should add some context here (it's a separate issue that this happens while running the parent build's settings script and isn't deferred).
- The build operation around configuring each child build doesn't describe which build is being configured, so the build script execution for child builds (which happens first) looks like it's running as part of configuring the parent build and that we're configuring the build a bunch of times.
