### ISSUE TITLE
Add more APIs to `File`-related configuration input tracking

### ISSUE THREAD

**Issue by h0tk3y** [gradle/gradle#23638]
More file-related APIs should be tracked and reported as configuration inputs.

For `File`:
- [ ] `list` (while `listFiles` is already there)
- [ ] `canRead`, `canWrite`, `canExecute`
- [ ] `lastModified`
- [ ] `length`
- [ ] `isHidden`
- [ ] maybe `getCanonicalPath` and `getCanonicalFile`, as those resolve symlinks

For Java NIO `Files`:
- [ ] `newInputStream`
- [ ] `newByteChannel`
- [ ] `newDirectoryStream`
- [ ] `isHidden`
- [ ] maybe `readSymbolicLink`
- [ ] maybe `isSameFile`
- [ ] `probeContentType`
- [ ] `getFileAttributeView`, `getAttribute`, `readAttributes`, `getPosixFilePermissions`, `getOwner`
- [ ] `isSymbolicLink`
- [ ] `isDirectory`
- [ ] `isRegularFile`
- [ ] `getLastModifiedTime`
- [ ] `exists`, `notExists`
- [ ] `isReadable`, `isWritable`, `isExecutable`
- [ ] `walkFileTree`, `walk`
- [ ] `newBufferedReader`
- [ ] `readAllBytes`, `readAllLines`, `lines`
- [ ] `list`
- [ ] `find`

For Java NIO `FileChannel`:
- [ ] `open`

For `FileSystemProvider` maybe:
- [ ] `newFileChannel`
- [ ] `newByteChannel`
- [ ] `newDirectoryStream`
- [ ] `newInputStream`

Kotlin stdlib extensions:
- [ ] `File.bufferedReader`
- [ ] `File.forEachBlock`
- [ ] `File.forEachLine`
- [ ] `File.inputStream`
- [ ] `File.readBytes`
- [ ] `File.reader`
- [ ] `File.readLines`
- [ ] `File.useLines`
- [ ] `File.walk*`
- [ ] maybe `URL.readText` and `URL.readBytes`

**Comment by ljacomet** [comment]
Thank you for your interest in Gradle!

This feature request is in the backlog of the relevant team and is prioritized by them.

**Comment by h0tk3y** [comment]
This is a copy of the list in the description that I'm working with, it only reflects my local state.

For `File`:
- [ ] `list` (while `listFiles` is already there)
- [ ] `canRead`, `canWrite`, `canExecute`
- [ ] `lastModified`
- [ ] `length`
- [ ] `isHidden`
- [ ] maybe `getCanonicalPath` and `getCanonicalFile`, as those resolve symlinks

For Java NIO `Files`:
- [ ] `newInputStream`
- [ ] `newByteChannel`
- [ ] `newDirectoryStream`
- [ ] `isHidden`
- [ ] maybe `readSymbolicLink`
- [ ] maybe `isSameFile`
- [ ] `probeContentType`
- [ ] `getFileAttributeView`, `getAttribute`, `readAttributes`, `getPosixFilePermissions`, `getOwner`
- [ ] `isSymbolicLink`
- [ ] `isDirectory`
- [ ] `isRegularFile`
- [ ] `getLastModifiedTime`
- [ ] `exists`, `notExists`
- [ ] `isReadable`, `isWritable`, `isExecutable`
- [ ] `walkFileTree`, `walk`
- [ ] `newBufferedReader`
- [ ] `readAllBytes`, `readAllLines`, `lines`
- [ ] `list`
- [ ] `find`

For Java NIO `FileChannel`:
- [ ] `open`

For `FileSystemProvider` maybe:
- [ ] `newFileChannel`
- [ ] `newByteChannel`
- [ ] `newDirectoryStream`
- [ ] `newInputStream`

Kotlin stdlib extensions:
- [ ] `File.bufferedReader`
- [ ] `File.forEachBlock`
- [ ] `File.forEachLine`
- [ ] `File.inputStream`
- [ ] `File.readBytes`
- [ ] `File.reader`
- [ ] `File.readLines`
- [ ] `File.useLines`
- [ ] `File.walk*`
- [ ] maybe `URL.readText` and `URL.readBytes`

**Comment by h0tk3y** [comment]
Progress on this is made in:
* https://github.com/gradle/gradle/pull/23925
* https://github.com/gradle/gradle/pull/24165

**Comment by h0tk3y** [comment]
The APIs that mutate the file system are tracked under this follow-up issue: 
* https://github.com/gradle/gradle/issues/24181
