### ISSUE TITLE
Migrate to JSpecify annotations

### ISSUE THREAD

**Issue by jvandort** [gradle/gradle#24767]
### Expected Behavior

Since we have now merged Kotlin `1.8.20` support into Gradle, we should now be able to migrate to JSpecify annotations. 

### Current Behavior (optional)

We currently use `javax.annotation.Nonnull` and `org.jetbrains.annotations.NotNull` annotations on Gradle's own `@NonNullApi`. We should investigate if we can instead annotate this annotation with one of JSPecify's annotations, or see if we can completely migrate to an alternative provided by JSpecify. 

### Context

Some things to consider:
* How would this change interact with `javax.annotation.Nullable` annotations we use on methods and fields in the codebase? 
* What is the migration path to using JSpecify annotations instead of `javax` annotations throughout the codebase?
* Will switching to JSpecify annotations affect Kotlin integration in any way in terms of source or binary compatibility. 
```[tasklist]
### Tasks
- [ ] https://github.com/gradle/gradle/pull/32306
- [ ] https://github.com/gradle/gradle/pull/32350
- [ ] https://github.com/gradle/gradle/issues/32370
- [ ] https://github.com/gradle/gradle/issues/26534
- [ ] https://youtrack.jetbrains.com/issue/IDEA-348069 - Local variables incorrectly marked non-null
- [ ] https://youtrack.jetbrains.com/issue/IDEA-356144 - JSpecify: Nullable upper bounds do not result in proper nullness
- [ ] Update all annotations to use JSpecify
- [ ] Keep existing javax annotations since these are still used by plugins/users
- [ ] Maybe blocking JSpecify issue with module/Java 8 support?
```

**Comment by octylFractal** [comment]
We should migrate to the [`NullMarked`](https://jspecify.dev/docs/api/org/jspecify/annotations/NullMarked.html) annotation instead of using `@NonNullApi`.

**Comment by eskatos** [comment]
The way the support for `provider.map { null }` was done in https://github.com/gradle/gradle/issues/19088 actually rely on a Kotlin compiler bug in handling nullability annotations. With jsr305 or jetbrains annotations it is currently impossible to represent that use case. JSpecify should work.

As part of this work we should make sure we can remove the workaround introduced in https://github.com/gradle/gradle/commit/c3168f2cc840e36beb350f3b1eba15d0ef0e94a0 that adds a kotlin compiler flag to restore the compiler bug (along with loooots of type system imprecisions).

**Comment by octylFractal** [comment]
Yes, it is.

**Comment by vlsi** [comment]
https://github.com/jspecify/jspecify#jspecify

> Any and all aspects of the API and specifications are subject to change prior to the 1.0 release. Using the annotations in a released library is not recommended.

:(

**Comment by octylFractal** [comment]
See the more recently-updated <https://github.com/jspecify/jspecify/wiki/adoption>, we feel it is safe to adopt now. Assuming there are no major issues and it improves Kotlin DSL nullness, it should be a net positive overall.

**Comment by kevinb9n** [comment]
Whoops, I should have fixed that wording on the main github page a while ago.

The jar is very safe to depend on. The absolute most we _might_ change in the actual artifact at this point would be to remove `@Target(METHOD)` from `@NullMarked` and `@NullUnmarked`. Even if you'd been using them on methods, it wouldn't cause you any trouble (worse than having avoided them in the first place) and should be a nonevent to clients as well. No other removals or renames (or the bizarre addition of a mandatory default-less attribute) will be considered.

**Comment by octylFractal** [comment]
Blocked by https://youtrack.jetbrains.com/issue/KT-59352 and another potentially related issue.

**Comment by eskatos** [comment]
[KT-59352](https://youtrack.jetbrains.com/issue/KT-59352) and the related blocking issue are both fixed in Kotlin 2.0.0-RC1.

**Comment by eskatos** [comment]
* About https://github.com/gradle/gradle/issues/12388

It seems that even if it could theoretically be possible to express this using JSpecify, there's no implementation commitment on the Kotlin side. IOW, migrating to JSpecify will not allow to resolve #12388.

**Comment by cpovirk** [comment]
Is there an easy way for me to help out from the JSpecify side? My guess would be that #12388 could be fixed by adding `@NullMarked` to `Transformer` without any further changes, since #23164 did most of what I would have done. (I could also make some other changes that I don't _think_ are necessary. But I'd start simple unless those changes turn out to be more necessary than I would think :)) I have tried to browse through various related issue, but I don't know if there's a standalone test that I could run easily with a Gradle built from head, so I'm not sure how easily I can test my claims.

For what it's worth, Kotlin has implemented enough JSpecify support that I would expect _that much_ to work today. I know that you've seen some other issues (as have those of us at Google in our usage of the JSpecify annotations with Kotlin), so I could understand if you want to wait until Kotlin 2+ is widely adopted before switching to JSpecify. I would only add that we have found the support to be good enough to use widely in our codebase, and the Kotlin developers have been of help when we've encountered problems.

**Comment by eskatos** [comment]
I made a local attempt at using JSpecify annotations together with Kotlin 2.1 and Kotlin language version 2.0 and it doesn't solve the https://github.com/gradle/gradle/issues/12388 case. Some implementation of the jspecify spec is missing in the Kotlin compiler as confirmed by a Kotlin compiler engineer.

**Comment by cpovirk** [comment]
Thanks. It's sad that it's not working.

You _might_ have better luck with language version 2.1, when Kotlin [began treating JSpecify annotations strictly](https://kotlinlang.org/docs/whatsnew21.html#change-of-jspecify-nullability-mismatch-diagnostics-severity-to-strict), but it seems like maybe that's experimental, maybe even more so with `kts`, and I haven't yet researched exactly what triggers the Kotlin behavior changes :( Another thing that might help is manually opting in at an older language version by passing `-Xjspecify-annotations=strict`. (Maybe you've tried these already. Maybe they should be unnecessary in the first place because of [this existing strictness setting](https://github.com/gradle/gradle/blob/80bf2a843e34cabf2493244612e5d4470685657d/build-logic-commons/basics/src/main/kotlin/gradlebuild/basics/kotlindsl/kotlin-compiler-configuration.kt#L61), but I'm not sure how much that affects.) However, I'm not sure I've managed to accomplish either of those, and I'm not even sure that I've managed to get the embedded Kotlin compiler to 2.1.0... :)

Even after a bunch of messing around, about all I can say is that I can make the error go away by removing `@NonNullApi`. Obviously, that's no accomplishment, especially because I haven't managed to then make the error _come back_ by adding `@NullMarked` while removing the existing `@Nullable` annotation on the type-parameter bound.

(Other discoveries: Groovy(?) seems to be confused ("syntax error @[29,42]") by the use of the JSpecify `@Nullable` over the JetBrains one (and even confused by use of JetBrains _`@NotNull`_ for some reason when I tested that for fun). I avoided that by sticking with the JetBrains `@Nullable` for now. And javac's `-Werror` is upset by how `NullMarked` has `@Target(..., MODULE)`, which is [unfortunately not something we found a way to avoid for people who build for Java 8](https://github.com/jspecify/jspecify/wiki/version-compatibility#issues-with-newer-versions-of-javac-and---release-8), at least without dropping support for module-level annotations (though I do wonder sometimes if we should have just done that anyway...). I avoided that by removing `-Werror`.)

I packed up my work on Gradle (which I was building with `-PbuildKotlinVersion=2.1.0` by the end of my experiment) and my work that used Caffeine (since that was a project with Kotlin Gradle configuration that I had handy) as a test for the rebuilt Gradle:

- https://github.com/gradle/gradle/compare/master...cpovirk:gradle:60adf2b2a7854c82f0dbab7ad9d358b983512371
- https://github.com/ben-manes/caffeine/compare/master...cpovirk:caffeine:ad937b33e041b53ef7a707b2151ad09e3e308cd5

**Comment by cpovirk** [comment]
(I don't know the Gradle codebase at all, but I have gotten the impression that it has some special nullness flags set for Kotlin in various areas, like [the strictness settings I linked above](https://github.com/gradle/gradle/blob/80bf2a843e34cabf2493244612e5d4470685657d/build-logic-commons/basics/src/main/kotlin/gradlebuild/basics/kotlindsl/kotlin-compiler-configuration.kt#L61) and also `-XXLanguage:+DisableCompatibilityModeForNewInference`+`-XXLanguage:-TypeEnhancementImprovementsInStrictMode`. (There are also the various places where `-language-version` is set to older values, but it sounds like you've looked into that part—and, for all I know, the others, too.) Again, without knowing the Gradle codebase, I can't tell how relevant that is to actual user build scripts. I will say that I've found that at least some of the `-XXLanguage` flags prevent mysterious-to-me errors in Caffeine, so it at least seems theoretically possible that they prevent kotlinc from including all the latest improvements to its nullness handling.)

**Comment by cpovirk** [comment]
(_But_ I just tried some simplified kotlinc experiments locally, and I was still seeing errors (or warnings with `-language-version 1.8`) even with those flags set. I will try to leave this alone now.)

**Comment by cpovirk** [comment]
OK, I will try to leave it alone _now_ :)

But it remains very strange to me. If I [annotate `Transformer` and `map` the way I'd expect](https://github.com/gradle/gradle/compare/master...cpovirk:gradle:62c92f57402e7dc1d6d8efb4f0fc1d2eade9c2db#diff-416164b914645f13eb6741f5e5821c14b5a84289681fb396a3c24a28466817a6R18), and if I write [a `map` call that should be allowed followed by two calls that should fail](https://github.com/ben-manes/caffeine/compare/master...cpovirk:caffeine:d055de1cd48e5422c39d81134ee999dfb0c8fee1#diff-c0dfa6bc7a8685217f70a860145fbdf416d449eaff052fa28352c5cec1a98c06R6), then I see only the two failures I expect **if I run kotlinc directly** (on `build.kt`, a symlink to my hacked-up `build.gradle.kts`):

```
$ $HOME/kotlin-compiler-2.1.0/kotlinc/bin/kotlinc -cp $HOME/clients/gradle-green/gradle/my-local-build/lib/gradle-core-api-8.13.jar build.kt
build.kt:8:59: error: argument type mismatch: actual type is 'kotlin.String?', but 'kotlin.String' was expected.
fun go2(g: DirectoryProperty): Provider<String> = g.map { n }
                                                          ^
build.kt:9:57: error: null cannot be a value of a non-null type 'org.gradle.api.Transformer<out S, in org.gradle.api.file.Directory!>'.
fun go3(g: DirectoryProperty): Provider<String> = g.map(null)
                                                        ^^^^
```

But when I run `$HOME/clients/gradle-green/gradle/my-local-build/bin/gradle tasks`, I see an error on all three lines:

```
Script compilation errors:

  Line 6: fun go(g: DirectoryProperty) = g.map { n }
                                                 ^ Type mismatch: inferred type is String? but String was expected

  Line 8: fun go2(g: DirectoryProperty): Provider<String> = g.map { n }
                                                                    ^ Type mismatch: inferred type is String? but String was expected

  Line 9: fun go3(g: DirectoryProperty): Provider<String> = g.map(null)
                                                                  ^ Null can not be a value of a non-null type Transformer<out TypeVariable(S)!, in Directory!>
```

This suggests to me that Kotlin's JSpecify support can handle the scenario fine but that I, at least, have been unable to trigger that support. Maybe I've ended up mixing [K1](https://github.com/gradle/gradle/blob/100e1722c075d384073614e1270f4eab0c89f197/platforms/core-configuration/kotlin-dsl/src/main/kotlin/org/gradle/kotlin/dsl/support/KotlinCompiler.kt#L126) and K2 APIs or something? If you folks have any interest in sharing a commit that sets up Kotlin 2.1 + language 2.0 more robustly, I'd probably continue playing around with things. But with the Kotlin-compiler people already involved, maybe it would be better if I didn't.... The main thing I'm noticing is that Kotlin _can_ handle this, if only I knew enough about Gradle to actually make the changes that I'd like to make.

**Comment by eskatos** [comment]
Thanks for your investigation @cpovirk!

I figured out a way to make it work with Kotlin 2.1 and Kotlin language 2.1. You must have only one domain of nullability annotations in a given module, otherwise things starts to break. For the `Transformer` example you need to migrate the whole `:core-api` module to JSpecify.

So, some progress on this but then I faced the fact that our backwards compatibility check based on JAPICMP, itself based on Javassist, can't make sense of `TYPE_USE` annotations (https://github.com/jboss-javassist/javassist/issues/223 and https://github.com/jboss-javassist/javassist/issues/15). I worked around that by using ASM in our custom rules.

Then another setback, we are using ArchUnit which also can't make sense of `TYPE_USE` annotations (https://github.com/TNG/ArchUnit/issues/1382). Still have to find a way around that.

**Comment by eskatos** [comment]
This will be addressed by
* https://github.com/gradle/gradle/pull/32492

FTR, ArchUnit has the necessary API to fall back to direct Java reflection, this allowed to easily adjust our rules.

I worked around the `ElementType.MODULE` problem by transforming the JSpecify JAR and removing this from the annotations in order for us to build and run on Java 8.

**Comment by octylFractal** [comment]
Bot is confused, https://github.com/gradle/gradle/pull/32492/commits/79a95d94ff75e1054758f079d55e4f3aa9e38f36 changes release notes.
