### ISSUE TITLE
Document new file permission API

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#24857]
* follow-up on #23983 

```[tasklist]
### Tasks
- [x] The Javadoc of ConfigurableFilePermissions should include a snippet showing how the API is used.
- [x] Update the user manual.  This could be added to Working With Files in the File copying in depth after [Filtering file content](https://docs.gradle.org/current/userguide/working_with_files.html#sec:filtering_files) and before [Using the CopySpec class](https://docs.gradle.org/current/userguide/working_with_files.html#sec:using_the_copyspec_class).
- [x] The Groovy DSL reference needs to be updated, e.g. [here](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:fileMode)
- [x] This is release notes worthy!
- [x] Release notes and upgrading guide should link to the user manual.
```
