### ISSUE TITLE
Switch Gradle to the new File Permissions API

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#24861]
* follow-up on #23983 

```[tasklist]
### Tasks
- [x] open issues with third-party plugins (Shadow & Spring Boot) to move to the new API once available
- [x] open a PR that adds the nagging so we have it ready (https://github.com/gradle/gradle/pull/24919)
- [x] declare the new API stable
- [x] third-party plugins using the new API are released
- [x] merge in above PR (when all other items are done)
- [x] prepare removal PR for Gradle 9 (https://github.com/gradle/gradle/pull/28436)
- [x] merge in the removal PR when master is `9.0-RC-1`
- [x] release a new version of the PlayFrameworkd plugin that doesn't use the deprecated API any longer (and use it as the tested version in `gradle/gradle` (https://github.com/gradle/gradle/issues/30530)
```

**Comment by jbartok** [comment]
Filed requests for upgrading major plugins to new API:
* https://github.com/johnrengelman/shadow/issues/892
* https://github.com/spring-projects/spring-boot/issues/37878

**Comment by jbartok** [comment]
Done!
