### ISSUE TITLE
Deprecate assemble task automatically building everything

### ISSUE THREAD

**Issue by big-guy** [gradle/gradle#26418]
By default, `assemble` depends on all artifacts that are attached to the archives configuration.

The archives configuration has all artifacts for all configurations that have visible=true in a project.

We should be more explicit with what is built by assemble.
```[tasklist]
### Tasks
- [ ] Deprecate behavior by detecting artifacts that are built implicitly
- [ ] Built-in plugins should explicit register what assemble means to them
- [ ] How do we handle different conventions?
- [ ] https://github.com/gradle/gradle/issues/32546
```

**Comment by ghale** [comment]
We've done the following:

- Removed the implicit building of artifacts (#32693)
- Deprecated Configuration.isVisible() and soft-deprecated setVisible() (#34079) 
- Created a follow up issue to fully deprecate setVisible() when kotlin is no longer using it (#34290)
- Created a draft PR to remove isVisible()/setVisible() in 10.0.0 (#34336)

I think we can track those remaining issues and close this one now.
