### ISSUE TITLE
☔ Kotlin DSL Reference

### ISSUE THREAD

**Issue by eskatos** [gradle/gradle#26486]
https://docs.gradle.org/current/kotlin-dsl/

```[tasklist]
### Issues
- [ ] https://github.com/gradle/gradle/issues/26286
- [ ] https://github.com/gradle/gradle/issues/24623
- [ ] https://github.com/gradle/gradle/issues/24622
```
