### ISSUE TITLE
Implement public Problems API

### ISSUE THREAD

**Issue by donat** [gradle/gradle#26953]
The goal is to allow publish problems from third-party plugins and consume them via the Tooling API

```[tasklist]
### Tasks
- [ ] https://github.com/gradle/gradle/issues/26954
- [ ] https://github.com/gradle/gradle/issues/26887
- [ ] https://github.com/gradle/gradle/issues/26948
- [ ] https://github.com/gradle/gradle/issues/26957
- [ ] https://github.com/gradle/gradle/issues/26997
- [ ] https://github.com/gradle/gradle/issues/27180
- [ ] https://github.com/gradle/gradle/issues/27123
- [ ] https://github.com/gradle/gradle/issues/27124
- [ ] https://github.com/gradle/gradle/issues/27182
- [ ] https://github.com/gradle/gradle/issues/27125
- [ ] https://github.com/gradle/gradle/issues/27358
- [ ] https://github.com/gradle/gradle/issues/27237
- [ ] https://github.com/gradle/gradle/issues/27241
- [ ] https://github.com/gradle/gradle/issues/27352
- [ ] https://github.com/gradle/gradle/issues/27354
- [ ] https://github.com/gradle/gradle/issues/27353
- [ ] https://github.com/gradle/gradle/issues/27356
- [ ] https://github.com/gradle/gradle/issues/27351
- [ ] https://github.com/gradle/gradle/issues/27350
- [ ] https://github.com/gradle/gradle/issues/27349
```
