### ISSUE TITLE
make custom gradle update script go away

### ISSUE THREAD

**Issue by xenoterracide** [gradle/gradle#27298]
### Expected Behavior

`./gradlew wrapper --write-locks --gradle-version 8.5` should do what I mean
`./gradlew dependencies --write-locks` should do what I mean

### Current Behavior (optional)

currently several workarounds are required to update gradle and locks correctly

### Context

I have this script

```sh
#!/bin/sh
# I exist because https://github.com/gradle/gradle/issues/27298
set -x
update_gradle() {
# https://github.com/gradle/gradle/issues/27295
    if test -n "$1"; then
        ARTIFACTORY_BASE_URL="myorg.jfrog.io/artifactory/gradle-distributions"
        ./gradlew wrapper --write-locks --gradle-distribution-url "https://$ARTIFACTORY_BASE_URL/gradle-$1-bin.zip" >&1 >/dev/null
    elif test -d "buildSrc"; then
        ./gradlew buildSrc:dependencies --write-locks
    fi
# gradle without the distribution url will overwrite our domain
}

# https://github.com/gradle/gradle/issues/21745
find . -name '*gradle.lockfile' -delete

# do it twice because https://github.com/gradle/gradle/issues/884
update_gradle $1
update_gradle $1

# https://github.com/gradle/gradle/issues/27297
./gradlew dependencies --write-locks 2>&1 >/dev/null
./gradlew spotlessApply --write-locks 2>&1 >/dev/null

set +x
```
and because I have subprojects it requires this task

```groovy
tasks.named('dependencies') {
    dependsOn(subprojects.collect { "${it.path}:dependencies" })
}
```

This is a silly amount of coding to do what gradle should just make easy out of the box. DWIM!

This is a meta ticket really meant to contain pointers to the individual tickets need to solve this problem

```[tasklist]
### Tasks
- [ ] https://github.com/gradle/gradle/issues/884
- [ ] https://github.com/gradle/gradle/issues/21745
- [ ] https://github.com/gradle/gradle/issues/27295
- [ ] https://github.com/gradle/gradle/issues/27297
- [ ] https://github.com/gradle/gradle/issues/27310
- [ ] https://github.com/gradle/gradle/issues/19081
```

**Comment by xenoterracide** [comment]
I've even gotten my script wrong like 3 times on here. It didn't work

**Comment by ov7a** [comment]
Sorry that you're having trouble with Gradle!

We appreciate the effort that went into filing this issue, but we must ask for more information. 

An explanation of what you are trying to solve with this feature request is a must for us to be able to reason about the use cases. Our available resources are severely limited, and we must be sure we are looking at the exact problem you are facing.

If we have a valid use case, we may be able also to suggest workarounds or ways to avoid the problem.

This issue will be closed after 7 days unless you provide more information.

***

It's confusing for me what are you trying to achieve with `./gradlew wrapper --write-locks --gradle-version 8.5`

**Comment by xenoterracide** [comment]
when you have a `buildSrc` with kotlin dependencies it adds kotlin to your lockfiles for the buildSrc. Gradle can break on update if you don't tell it to write the locks again.

**Comment by ov7a** [comment]
Can you please provide a minimal reproducer to demonstrate the issue with Kotlin dependency locks you are experiencing?

The ideal way to provide a reproducer is to leverage our [reproducer template](https://github.com/gradle/gradle-issue-reproducer). You can also use [Gradle Project Replicator](https://github.com/android/project-replicator) to reproduce the structure of your project.

**Comment by xenoterracide** [comment]
do you want a reproducer that reproduces *all* of the issues? or just why `--write-locks` is needed with `wrapper`

**Comment by ov7a** [comment]
I was asking for `--write-locks` specifically.

As for the problem, "make custom gradle update script go away" is your specific case. If it is covered in other issues, we'll close this issue as a duplicate.

**Comment by caleb-cushing0-kr** [comment]
do what though wilt I guess. I don't feel like I've been given a reason to explain why locks need to be updated when you lock buildSrc when you update gradle and have kotlin plugins.
