### ISSUE TITLE
Introduce smoke test fixing the amount of IP violations observed from Sync with IDEA

### ISSUE THREAD

**Issue by bamboo** [gradle/gradle#27364]
- [x] Extract AS provisioning machinery to separate `studio-provisioning-plugin`, and use it `performance-test-plugin` #27499
- [x] Create dedicated `smoke-ide-test` subproject project #27515 
- [x] Add `smokeIdeTests` run on CI #27515 
- [ ] ~~Migrate `studio-provisioning-plugin` to [intellij-ide-starter](https://github.com/JetBrains/intellij-ide-starter/tree/master)~~ Won't be fixed
- [x] Use `ide-starter` directly in `smoke-ide-test` to run IDEA #28526
