### ISSUE TITLE
Integrate Java compiler with the problems API

### ISSUE THREAD

**Issue by hegyibalint** [gradle/gradle#27596]
## Goal

The Java compiler outputs compilation problems directly to the standard output. The problem with that is that the information is buried in the build output, and users must scroll up in the build log to figure out what made the build fail. This is a subpar experience, which we could improve by integrating the compiler task with the Problems API. By using the API, we can create a comprehensive report at the end of the build.

In addition to the reporting capabilities, structured problems could help IDEs and tools establish what went wrong and where. This is already the case in some of the tools, but it relies on parsing the console output vs. receiving well-defined, structured information about what happened. As an example, build scans can render a separated, focused report about compilation problems, which doesn't rely on the console output.

## Resources

- [Specification - Java Compiler Diagnostics as Problems](https://docs.google.com/document/d/1RWyPU6dXxZehx5XWpNQU9957gNCTjvGEAiIfUDqdAGc)

## Deliverables

- [x] Custom `DiagnosticListener` for the Java compiler task emitting Problem events and delegate to default rendering
  - [x] Problem reports describing individual compiler warnings/errors/notes/etc.
  - [x] Problem reports describing problems with the compilation process itself
    - [x] compileJava tasks fails because there were warnings and `-Werror` is specified. 
    - [x]  compileJava tasks fails because of invalid compiler argument problems: `javac -source -1`
 - [x] Describe new feature in release notes (`IDE Integration improvements` section)

## Acceptance criteria

- [x] Stakeholders are informed about the new features
- [x] Our team in 👍  on the data as it will be the input for the upcoming compilation build failure console rendering improvements.

## Stakeholders

- BT JVM team (as code-owners for the java compilation component)
- Piotr
- JetBrains
- Google
-  Microsoft VSCode team

## Communication plan

- JVM team
  -  get buy-in on planned feature
  - update them weekly on progress
- JB/Google/Microsoft: 
   - notify them about deliverables when something changes
   - keep them updated on regressions/etc

## Associated tasks

```[tasklist]
### Tasks and issues
- [ ] https://github.com/gradle/gradle/issues/25707
- [ ] https://github.com/gradle/gradle/issues/26529
- [ ] https://github.com/gradle/gradle/issues/27770
- [ ] https://github.com/gradle/gradle/issues/27823
- [ ] https://github.com/gradle/gradle/issues/27829
- [ ] https://github.com/gradle/gradle/pull/27998
- [ ] https://github.com/gradle/gradle/issues/27693
- [ ] https://github.com/gradle/gradle/issues/27948
- [ ] https://github.com/gradle/gradle/pull/27960
- [ ] https://github.com/gradle/gradle/pull/29080
- [ ] https://github.com/gradle/gradle/pull/28281
- [ ] https://github.com/gradle/gradle/issues/28554
- [ ] https://github.com/gradle/gradle/pull/29063
- [ ] https://github.com/gradle/gradle/issues/28930
- [ ] https://github.com/gradle/gradle/issues/29113
- [ ] https://github.com/gradle/gradle/issues/29406
- [ ] https://github.com/gradle/gradle/pull/29352
- [ ] https://github.com/gradle/gradle/issues/29423
- [ ] https://github.com/gradle/gradle/pull/29421
- [ ] https://github.com/gradle/gradle/issues/29493
- [ ] https://github.com/gradle/gradle/issues/29501
- [ ] https://github.com/gradle/gradle/pull/29605
```

**Comment by AndreasTu** [comment]
It would be great if that new API is also exposed to Gradle-Plugins not only Tooling API (like. IDEs).

**Usecase:**
I would like to implement a GradlePlugin which tracks the Java compile warnings and let the build fail if new warnings are added, but existing warnings are "accepted" for the time being. This would allow projects to gradually migrate to the `-Werror` without enforcing to fix all warnings at once. The Plugin would then update the accepted warnings during build, when old warnings are fixed. If the warning count drops to zero the `-Werror` flag will be enforced.

The API would allow me to implement such a thing, because it would be able to track the occurred warnings reliably.

**Comment by tbroyer** [comment]
Might be a moonshot but it could be a good idea to define a "standard" API for diagnostics to allow passing fix suggestions to the Problems API, so that IDEs could provide a "quick fix" action for example.

Error Prone for instance produces such suggestions, and having them surfaced somehow down to the Problems API through the compiler diagnostics could allow IDEs to propose them as "quick fixes" directly.
I made some research and a POC last year that was Error Prone specific but could likely be turned into some "standard" API: the idea was putting those fixes into an object passed as first argument to the diagnostic message; without a specific diagnostic listener, the object's `toString()` is called when the message is formatted and you get an standard message, but with a specific diagnostic listener it can cast the argument to that "standard" API and extract structured information out of it. The POC relied on the very few message-bundle keys used by Error Prone to detect when such a structured-information would be known to be available.
This would of course require tools like Error Prone to collaborate and use your "standard API" though.

The feature request for the Gradle GitHub Action to surface problems reported through the Problems API as comments on pull request (https://github.com/gradle/gradle-build-action/issues/1061) could take advantage of such structured information to add GitHub suggestions to the comments as equivalent to IDE "quick fixes" too.
