### ISSUE TITLE
Allow configuring Java feature preview in DSL

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#28540]
### Expected Behavior

It should be easy to start working with Java feature previews.

```kotlin
java {
    enablePreviews()
}
```

This should be enough to enable previews across compilation, tests and exec tasks.

The Javadoc task should probably be included as well. There were [user reports](https://github.com/gradle/gradle/issues/27001#issuecomment-1803632810) previously that hinted on that.

### Current Behavior (optional)

You are forced to configure feature previews on the task level, and also using raw JVM args.

https://docs.gradle.org/current/userguide/building_java_projects.html#sec:feature_preview

### Context

JDK authors deliver new previews with almost every new release, which is happening relatively fast these days.

IntelliJ allows switching to previews with a single action. After activating it, users are given an impression that the preview features fully work with their project, because in-editor errors disappear. However, as soon as they try to run the build via Gradle, things break, because feature previews have to be configured there separately, and on a low task-level as well.
```[tasklist]
### Tasks
- [ ] https://github.com/gradle/gradle/pull/28544
- [ ] Support enabling preview for exec-like tasks
- [ ] Support enabling preview for javadoc
- [ ] Consider unifying the enable preview APIs across tasks
- [ ] Update userguide to include the new APIs
- [ ] Consider introducing higher level configuration to enable preview
```

**Comment by alllex** [comment]
I am not sure if this also be integrated with Groovy and Scala tasks out-of-the-box. It likely should, since we usually share the same JVM options with those plugins.

An additional consideration is the `release` option. In order to [enable previews for a particular release](https://docs.oracle.com/en/java/javase/21/language/preview-language-and-vm-features.html), Java compiler users can also explicitly set the `--release` or `-source` options. The `release` option we expose in the DSL does not have a convention, but the source compatibility should be defaulting to the toolchain if not explicitly configured. So the preview enabling should work nicely with the toolchains.

**Comment by ov7a** [comment]
Related:
* https://github.com/gradle/gradle/issues/27001
* https://github.com/gradle/gradle/issues/12984
