### ISSUE TITLE
Publish Gradle API

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#29483]
TBD

```[tasklist]
### Tasks
- [ ] https://github.com/gradle/gradle/pull/29320
- [ ] https://github.com/gradle/gradle/pull/29481
- [ ] Sign published artifacts.
- [ ] Fix Kotlin DSL compilation to have access to extension methods
- [ ] Publish artifacts under final GAV.
- [ ] Include API JAR in Gradle distribution, and compile against it when using `gradleApi()`.
- [ ] Publish sources.
- [ ] Publish Javadocs.
- [ ] Move all logic to publish API JARs to its own build-logic plugin.
```

**Comment by ljacomet** [comment]
Gradle 8.14 publishes an experimental API JAR.

* Coordinates: `org.gradle.experimental:gradle-public-api`
* Repository: https://repo.gradle.org/artifactory/libs-releases/
* Content: Similar to the generated Gradle API JAR in the distribution. This means it still contains most `internal` types.
* Metadata: API only variant, with a non default capability. This is done to allow us to add a proper, public API only, default variant in the future.

Note that the experimental nature is mostly tied to the Gradle development plugins not having any support for this API jar yet. If you want to play with it, you will have to do the necessary work to remove the default `gradleApi` dependency and use this one instead.

Usage:
```
compileOnly("org.gradle.experimental:gradle-public-api:<version>") {
    capabilities {
        requireCapability("org.gradle.experimental:gradle-public-api-internal")
    }
}
```

Note: At the time of writing, `8.14` is not yet released, but `8.14-rc-1` is.

**Comment by martinbonnin** [comment]
That's going to be super helpful for plugin developers , thanks ! 

Out of curiosity, are there any plans to release on Maven Central? There's always a bit of friction with adding more repositories.

**Comment by 3flex** [comment]
@ljacomet there are older versions in that repo too, back to 8.9, I assume as part of https://github.com/gradle/gradle/pull/29320. Are any older versions suitable for use at this point, or only 8.14+?

**Comment by remal** [comment]
https://github.com/orgs/remal-gradle-api/packages?repo_name=packages

I use these packages to develop my Gradle plugins.

**Comment by ljacomet** [comment]
@martinbonnin Yes, we would like to release on Maven Central. But maybe not until we move to the final coordinates.

@3flex There were some fundamental changes between what we tried and the 8.14 version. Between the difference in dependency declaration and content, I would not necessarily try them out.

**Comment by bamboo** [comment]
It seems the published metadata is missing the Kotlin dependencies (cc @ljacomet ).

**Comment by ihostage** [comment]
Hi, @ljacomet! 👋 
Will `org.gradle.deployment.internal.DeploymentHandle` be a part of published API?
It's related to https://github.com/gradle/gradle/issues/2336

**Comment by nskvortsov** [comment]
We will be changing the IntelliJ IDEA codebase to consume this API soon (November)
