### ISSUE TITLE
Untangle Service Registry framework implementation

### ISSUE THREAD

**Issue by alllex** [gradle/gradle#29596]
Eventually, Gradle's internal dependency injection framework, which is based on Service Providers, should be refactored to cleanly separate its API and implementation.

### Tasks
- [ ] https://github.com/gradle/gradle/pull/29566
- [ ] https://github.com/gradle/gradle/pull/29584
- [ ] https://github.com/gradle/gradle/pull/29574
- [ ] https://github.com/gradle/gradle/pull/29599
- [ ] https://github.com/gradle/gradle/pull/29608
- [ ] https://github.com/gradle/gradle/pull/29607
- [ ] https://github.com/gradle/gradle/pull/29617
- [ ] https://github.com/gradle/gradle/pull/29609
- [ ] https://github.com/gradle/gradle/pull/29623
- [ ] https://github.com/gradle/gradle/pull/29632
- [ ] https://github.com/gradle/gradle/pull/29622
- [ ] https://github.com/gradle/gradle/pull/29659
- [ ] https://github.com/gradle/gradle/pull/29658
