### ISSUE TITLE
Disallow infix function calls in Declarative DSL

### ISSUE THREAD

**Issue by jbartok** [gradle/gradle#30677]
### Issue type

Polishing

### Problem description

Currently, DCL syntax/grammar allows for infix function calls. The main reason for that is the `plugins` block, where the infix notation was/is the recommended way to specify plugin IDs and versions in the Kotlin DSL. Since we want Kotlin DSL content to be copy-pastable in DCL (as long as it's declarative enough), we kept the infix notation in the allowed syntax.

However, the infix notation breaks one of the basic tenets of the Declarative DSL, namely the restriction of having only one way of doing one thing. We must allow for regular function calls, so the infix notation is extra. We should get rid of it.

```[tasklist]
### Tasks
- [x] Remove the infix notation from the grammar
- [ ] Modify the parser, make it not supported
- [ ] Remove its handling from higher level interpretation steps
```

**Comment by jbartok** [comment]
This issue is obsolete, we need infix functions for map support (even if we only allow for the `to` function).
