### ISSUE TITLE
De-incubate strongly-typed dependencies block API

### ISSUE THREAD

**Issue by octylFractal** [gradle/gradle#30872]
```[tasklist]
### Tasks
- [x] https://github.com/gradle/gradle/issues/32021
- [ ] Remove supertype of `MinimalExternalModuleDependency` to reduce dependency interface issues
- [ ] Determine if we can give all version catalog providers a supertype to reify the `Provider` generic and allow them to coexist with other `DependencyCollector#add`, or other solution that would help with this.
- [ ] If not, add `addCatalog` and do hacks in Groovy and Kotlin to allow invoking without issues
- [ ] De-incubate!
```

**Comment by octylFractal** [comment]
Open question: should `DependencyCollector#bundle` support only version catalog or `List<Dependency>`? In general the team is not a fan of `bundle`, so perhaps it might be better to keep it limited, but support for moving existing Groovy top-level `dependencies {}` usage may be desired. But we could always add that support in the extension as well.

**Comment by tresat** [comment]
This interface is no longer `@Incubating`, we should update this issue.
