### ISSUE TITLE
Support file-system watching on Alpine/musl

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#30885]
In Gradle 8.8 we disabled native services on Alpine/musl, because it was causing core dumps:

- https://github.com/gradle/gradle/pull/28258
- https://github.com/gradle/gradle/issues/24875

However, Alpine is used more an more as a developer virtual machine, so having file-system watching available would be nice.

When file-event handling was moved from `native-platform` to the `gradle-fileevents` library, we also added support for Alpine/musl. The native libraries are now available for Alpine on both `x86_64` and `aarch64` since:

- https://github.com/gradle/gradle/pull/30294

The support is not yet enabled, though, because we had no testing on Alpine. 
## TODO

- [x] Re-enable native services on musl by removing the check in `NativeServices.shouldUseNativeIntegration()`.
- [x] Run quick feedback tests on Alpine / musl on TeamCity as part of ready-for-release. -- https://github.com/gradle/gradle-private/issues/4511
- [x] https://github.com/gradle/gradle/pull/31287
- [x] https://github.com/gradle/gradle/pull/31291

**Comment by lptr** [comment]
This was done via https://github.com/gradle/gradle/pull/31096/files#diff-5dc2bde814f49800b46cd797257594c19792ab92c946711d15f7b60b7b56ca32.

**Comment by lptr** [comment]
We should still mention that file-system watching on Alpine is now supported in the docs.
