### ISSUE TITLE
Support Windows ReFS

### ISSUE THREAD

**Issue by lptr** [gradle/gradle#31634]
ReFS is becoming popular, and is actually being recommended as the file-system of choice for software development by Microsoft:

- https://learn.microsoft.com/en-us/windows/dev-drive/ (Aug 2024)
- https://devblogs.microsoft.com/visualstudio/devdrive/ (May 2023)

Gradle does not currently support ReFS directly. It seems to be able to run builds, though without the benefits of file-system watching. There are also other problems with some ReFS-specific features.

Let's support ReFS as a first-class citizen by adding tests and fixing known issues we currently have.

## TODO

- [ ] Revert https://github.com/gradle/gradle/pull/31464
- [ ] Set up testing infrastructure - https://github.com/gradle/gradle-private/issues/4543
- [ ] https://github.com/gradle/gradle/issues/30808
- [ ] https://github.com/gradle/gradle/issues/26225

**Comment by lptr** [comment]
Ran some tests with ReFS on `windows144`.

Cloning `gradle/gradle` locally from one directory to another:

- NTFS: 9.25-9.75 sec
- ReFS: 6.49-6.86 sec

That's 25-33% faster on ReFS!

Deleting the cloned directory:

- NTFS: 6.38 sec
- ReFS: 3.50 sec

That's 46% faster. Nice!

**Comment by tcfurrer** [comment]
@lptr Yes but without filesystem watching, wouldn't large incremental builds get significantly slower despite the inherent performance advantages of ReFS? Is it even _feasible_ for gradle to support vfs file watching on ReFS?

**Comment by dieterstueken** [comment]
I'm also faced by the problem, since I also enabled a 'dev drive' using ReFS.

One thing I noticed already: the problem described by [issue 30808](https://github.com/gradle/gradle/issues/30808) happens with de-duplicated files on NTFS. Those are implemented by special files called [reparse-points](https://en.wikipedia.org/wiki/NTFS_reparse_point).

However, as I understand it, de-duplication on ReFS happens on the block-layer and is fully transparent to the file system layer. But I'm not absolutely sure, since ReFS also supports reparse-points, too. So I think the problem is not related to ReFS de-duplication but a problem with ReFS in general.

I can try to analyze issues 26225 with my own project the next days to get a better understanding of the problem.

**Comment by cschoell** [comment]
The DevDrive in Windows requires ReFS - and it is the only way to enable asynchronous scanning in most secured environments (making development with windows antivirus a lot less painful). 

It works rather well - having to turn of VFS file watching reduces the performance gain again though. It would be awesome to see ReFS support in gradle.

**Comment by lukeu** [comment]
To add some context, my team was assimilated into a large corp and issued laptops with >50% faster specs, yet builds ran 2x slower. So I put a lot of time into looking for solutions. Dev Drive coming along was the only thing that finally improved build performance, given the locked-down MS scanners (which have long punished Java) and remotely-managed corporate crapware.

I think it should be in corporate Windows developers' **first** interests to adopt ReFS, if they haven't yet done so. This will be much more significant than any other perf tweaks which may be in the pipeline - compared with building with the handbrake still applied.

Which is all just to say, once Gradle does gain full support - it might be nice to help promote it in the release notes as a potentially _very_ significant build-performance tweak.
