### ISSUE TITLE
Improve publishing plugin documentation

### ISSUE THREAD

**Issue by oehme** [gradle/gradle#4941]
There are a lot of questions around publishing best practices, which we should address in the user guide or samples. Here are some examples from our issue tracker and forum:

- [X] ~How do I publish to Maven Central (javadoc jar, source jar, required POM info)~ → #5094 
- [X] ~How do I put snapshots in a different repository than releases?~ → #5095 
- [X] ~How can I [control where to publish](https://discuss.gradle.org/t/maven-publish-destination-repo-snapshot-release-from-another-task/20641) using a command line argument or environment variable?~ → #5095
- [X] ~How can i disable signing for snapshots/local builds?~ → #5096 
- [X] ~How do I customize the published metadata (POM/IVY file)?~ → documentation will be updated as part of #3348
- [X] ~How can I publish additional artifacts, e.g. sources?~ → #5097 
- [X] ~Where and how should I store credentials?~ → #5112 
- [X] ~Is there a way to publish a [dynamic set of artifacts](https://discuss.gradle.org/t/maven-publication-closure-is-evaluated-too-early/19911/6)?~ → #5293
- [X] ~How do I publish only some publications?~ → #5116
  - ~Users are [overwhelmed](https://discuss.gradle.org/t/disable-maven-publish-related-tasks-not-possible/13488/5) by the number of tasks involved and disable only one of them, all others are still run though~
  - ~Users want to put [some artifacts in one repo and some into another](https://discuss.gradle.org/t/publish-groups-of-artifacts-to-multiple-repos-based-on-artifact-type/22497), based on some criteria~
- [X] ~Users want to create [short-hand tasks](https://discuss.gradle.org/t/deploy-with-maven-publish-using-your-own-task-instead-of-auto-generated/22329) for running only some of their publications.~ → #5116
- [ ] How do I publish an existing POM file instead of letting Gradle generate one?
- [ ] Can I publish only the modules that have changed?
- [X] ~How do I publish a BOM?~ → #5292

**Comment by marcphilipp** [comment]
I'm closing this epic because the most important items have been addressed. I create two follow-up issues, namely an #5292 and #5293, for two remaining items I deemed important.
