### ISSUE TITLE
Include Kotlin DSL samples in all user manual chapters

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#6442]
Kotlin DSL 1.0 RC is upon us. Now that the APIs are stable, it is time for Kotlin DSL examples to be displayed everywhere in Gradle documentation that the Groovy DSL is.

This epic will be considered complete when all samples within the [user manual in Gradle nightly](https://docs.gradle.org/nightly/) distribution have a Kotlin DSL sample alongside the Groovy DSL sample.

### Contributor Instructions

If you are familiar with the Gradle Kotlin DSL and want to help the project reach the 1.0 milestone. 

- [ ] [Setup your environment for developing Gradle](https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#development-setup). Don't forget to set at `java9Home` Gradle property! (e.g. `echo "systemProp.java9Home=/Library/Java/JavaVirtualMachines/jdk-9.0.4.jdk/Contents/Home" >> ~/.gradle/gradle.properties`)
- [ ] Submit an empty pull request titled "Include Kotlin DSL samples for chapter (chapter_name)" or write a comment on this issue for 1 user manual chapter (at a time). See the table below or consult the [list of all chapters](https://github.com/gradle/gradle/tree/master/subprojects/docs/src/docs/userguide).
- [ ] Open the appropriate chapter under the `subprojects/docs/src/docs/userguide/` in your gradle/gradle clone.
- [ ] Generate the user manual by running `./gradlew :docs:userguide -x :docs:userguideSinglePage` and serving the content under `subprojects/docs/build/docs`.
- [ ] For each "Example" in the `.adoc` file in question, create a [multi-language sample listing](https://github.com/gradle/gradle/tree/master/subprojects/docs#code-samples). You will have to move around files and create a sibling `kotlin/` project which should have identical functionality to the `groovy/` one, `include` the Groovy and Kotlin samples next to each other, and configure the sample tests. _Don't forget to update any tests/other documents that reference the given sample._

This is a diff that shows what this looks like: https://github.com/gradle/gradle/pull/6508/files#diff-ce02749237d61352d70ff3c9746a5e59R58

When writing Kotlin DSL samples please:
- keep them as similar as possible to the Groovy sample
- make both Groovy and Kotlin samples prefer the `plugins {}` block to apply plugins
- make sure all sample builds have a `settings.gradle` or `settings.gradle.kts` file and a reasonable `rootProject.name`
- do not adopt the lazy configuration API or overuse Kotlin language features
- if you find any missing type-safe member in the Gradle API then create an issue on `gradle/gradle` and work around it by e.g. leveraging `closureOf(..)` or `withGroovyBuilder {}`

The [Migrating from Groovy to Kotlin DSL guide](https://guides.gradle.org/migrating-build-logic-from-groovy-to-kotlin/) will be helpful here in addition to [Kotlin DSL samples](https://github.com/gradle/kotlin-dsl/tree/master/samples).

- [ ] After making changes, run samples tests using `./gradlew :integTest:integTest --tests "UserGuideSamplesIntegrationTest"` or even a subset with `./gradlew :integTest:integTest --tests "UserGuideSamplesIntegrationTest.*foobar*"`
- [ ] Push to your branch and let us know it's ready for review.
- [ ] Address any feedback to get your pull request merged. Congratulations! Email developer-experience@gradle.com with a link to your first merged pull request and we'll send you Gradle swag as thanks!

Example PRs for inspiration: #6434 #6406 #6424 

If you get stuck, reach out to us through the `#kotlin-dsl` channel on [Gradle Community Slack](https://gradle-community.slack.com/). [Invite link](https://join.slack.com/t/gradle-community/shared_invite/enQtNDE3MzAwNjkxMzY0LTYwMTk0MWUwN2FiMzIzOWM3MzBjYjMxNWYzMDE1NGIwOTJkMTQ2NDEzOGM2OWIzNmU1ZTk5MjVhYjFhMTI3MmE).

### Remaining Work

| Chapter | # Samples | Status |
| --- | --- | --- |

**Comment by StefMa** [comment]
Hey @eriwen 
you can assign me the `./java_gradle_plugin.adoc` 👍

**Comment by jnizet** [comment]
I'm working on working_with_files.adoc

**Comment by StefMa** [comment]
@jnizet i like your enthusiasm of adding the Kotlin DSL to the docs.
But it would be great to don't mention the ticket issue on *each* of your commit.
This issue here got unmaintainable 🙈

**Comment by jnizet** [comment]
@StefMa I'm just following the official guidelines here: https://github.com/gradle/gradle/blob/master/CONTRIBUTING.md#creating-commits-and-writing-commit-messages

**Comment by jnizet** [comment]
@eriwen Many chapters use samples from several different projects, and those projects contain samples for many chapters (i.e. there is a many-to-many association between chapters and sample projects).

So if we try to create a PR for a chapter, we frequently have to translate several samples, and thus affect several other chapters too. 

I think it would be easier to identify the samples that are used in the user guide chapters, and then split the work by samples, rather than splitting it by chapters: leaving a .adoc file half-translated is fine, but leaving a sample half-translated isn't. 

Something like

 - userguide/java/basic: used in chapters
    - building_java_projects
    - java_testing
 - userguide/java/customDirs: used in chapters
    - building_java_projects
    - java_testing

Listing the chapters isn't even absolutely necessary: we can easily find all the .adoc files where a given sample is being used, and modify all these chapters when we translate a sample.

The PR title would simply have to be changed to "Translate user-guide sample (sample-name) to Kotlin DSL"

What do you think?

**Comment by mkobit** [comment]
Is it worth creating`kotlin-dsl` samples for:

* `userguide/software_model.adoc`
* `userguide/software_model_extend.adoc`
* other software model (native maybe?)

The examples are going to look considerable different than the Groovy due to the need for `RuleSource` extending plugins.

**Comment by eskatos** [comment]
Good point @mkobit! The software model is deprecated and its `model {}` block isn't supported by the Kotlin DSL, so let's leave the software model chapters untouched.

**Comment by mkobit** [comment]
What about the guides at https://guides.gradle.org ?

**Comment by StefMa** [comment]
These are not part of this repository but should be updated too.

**Comment by jnizet** [comment]
@mkobit @StefMa several of them have already been translated. I translated one or two of them IIRC. The main difference is that these guides don't use exemplar for tests, and the way tests are written varies from guide to guide.

**Comment by eriwen** [comment]
We do want to convert the guides, too. @jnizet is right that we'd probably want to convert them to use [Exemplar](https://github.com/gradle/exemplar/) for testing (most don't yet). It's tougher for me to write instructions because some guides use slightly different plugins/libraries. 

That all said, I probably will put together a similar issue to this one on the gradle/guides board and at any time happy to help contributors eager to improve guides. Please reach out.

**Comment by eskatos** [comment]
This is now done! Thank you all!
