### ISSUE TITLE
Remote Init Scripts

### ISSUE THREAD

**Issue by eriwen** [gradle/gradle#745]
Effectively, a way to have a build always apply an init script available via a HTTP URL when executing. Imagine a line item in wrapper.properties or similar with the location of one or more scripts. This is a long desired feature with many uses, but in our context would be leveraged to at least provide the logic to build the custom plugin repo definition.

Example: `apply from: "https://myservice.example.com/foobar"`
- [ ] Look into ordering of plugin repositories resolution
- [ ] Respect caching headers of given remote resource
- [ ] Expired resource should still be used in `--offline` mode

**Comment by oehme** [comment]
This Epic should not be called "remote init scripts". Init scripts are decorative (i.e. a build should work without them). If something is part of the build's definition (like the plugin repositories to be used), it should be applied as a settings script. The `Settings` instance also has access to all methods of the `Gradle` instance and thus can do anything an init script could do. This should already be possible:
```
pluginRepositories {
  apply from: 'http:\\.../plugin-repositories.gradle', to: pluginRepositories
}
```

In `plugin-repositories.gradle`:

```
maven {
  url = '...'
}
```

**Comment by oehme** [comment]
Another use case is defining plugin repositories from within a custom Gradle distribution. This will also be possible once the `pluginRepositories` block has become a normal DSL method on `Settings` (as part of #1343). Then users can use the [settingsEvaluated()](https://docs.gradle.org/current/javadoc/org/gradle/BuildListener.html#settingsEvaluated(org.gradle.api.initialization.Settings)) method to add plugin repositories from an init script inside a custom Gradle distribution. But this is a local init script (part of the distro), not a remote one.
