### ISSUE TITLE
Epic: Road to Gradle metadata 1.0

### ISSUE THREAD

**Issue by melix** [gradle/gradle#8380]
## Context

This story summarizes work we need to do in order to release Gradle metadata 1.0:

- [x] Fix variant disambiguation not preferring the variant that has the most common requested attributes (#8395)
- [x] Add a standard `bundling` attribute to the Java ecosystem to handle the common "repackaged" use case (#8455)
- [x] Fix inconsistent compatibility rules in Java (#8370)
- [x] Update `addVariantFromConfiguration` _not_ to use a name and use outgoing variants instead (#8383)
- [x] Provide similar API to `addVariantFromConfiguration` for adhoc publications (#8399)
- [x] Rework Java publishing so that it uses outgoing configurations _as is_ (same attributes) instead of mapping (#8399)
- [x] <s>Consider enabling Gradle metadata by default</s> _not in 5.3_
- [x] Consider markers in POM files to use Gradle metadata if we don't enable Gradle metadata by default (#8426)
- [x] Add a `JAVA_API_JARS` usage for consistency with `JAVA_RUNTIME_JARS` (#8433)
- [x] Make Gradle metadata 1.0 (#8525)
- [x] Document Gradle metadata 1.0 (#8525)

Optional:

- [ ] <s>Consider "ecosystem"/"domain" property in Gradle metadata to indicate that some attributes require the application of a plugin which understands the domain</s>
- [ ] Strategy to discover that a "classifier" in a POM file corresponds to a specific variant in a published Gradle metadata file (aka Maven interoperability)
- [x] Add a standard "javaTargetPlatform" attribute to the Java ecosystem (in order to be able to publish multiple versions of a single library, #8554)

**Comment by ljacomet** [comment]
Created #8638 for the remaining optional item.
Closing this one as the work is ready to ship with Gradle 5.3
